### ISSUE TITLE
Create a typescript team meetings

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/typescript#1]
lets choose a time/day of the week for the team meeting
it's ok if you are not available in the date I added in the doodle, I understand the short notice, we can start with regular meeting in september.
https://doodle.com/meeting/participate/id/erMKy1Kd

If you want to be added to the team https://github.com/orgs/nodejs/teams/typescript, please request membership

@nodejs/collaborators @nodejs/loaders @nodejs/typescript 
 
@DanielRosenwasser @jakebailey @kdy1 can I add you to the team?

**Comment by jakebailey** [comment]
Yes, go ahead and add me.

**Comment by marco-ippolito** [comment]
Ill leave the doodle open until friday

**Comment by jakebailey** [comment]
If you've voted on it, note that there is a second page of times (doodle's UI isn't very obvious IMO).

**Comment by kdy1** [comment]
Of course!

**Comment by Lxxyx** [comment]
Just sharing some news.

Yesterday, I shared the news on social media that Node.js has started to experimentally support running TypeScript and launched a survey. As of the time of my reply, a total of 130 developers have voted. The results are as follows (all participants are developers from China):

- Support: 80 votes (62%)
- Against: 25 votes (19%)
- Neutral: 25 votes (19%)

**Comment by khaosdoctor** [comment]
Hello I'd like to be a part of the group as well

**Comment by marco-ippolito** [comment]
@khaosdoctor 
For everyone else please fill the doodle https://doodle.com/meeting/participate/id/erMKy1Kd

**Comment by marco-ippolito** [comment]
Winner is Wednsday from 5.30 to 6.pm CEST. Doodle is closed

**Comment by khaosdoctor** [comment]
> Winner is Wednsday from 5.30 to 6.pm CEST. Doodle is closed. I'll go ahead and create the recurring meeting

Is the link being sent directly to our emails? I haven't received anything yet.

**Comment by DanielRosenwasser** [comment]
Yes please add me

**Comment by andrewbranch** [comment]
Can you add me, please?

**Comment by marco-ippolito** [comment]
added both

**Comment by marco-ippolito** [comment]
@nodejs/typescript team created, recurring meeting setup on the calendar https://calendar.google.com/calendar/u/0/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98@group.calendar.google.com 
First meeting Wednesday 28th August
