### ISSUE TITLE
Add zoom link to recurring calendar invite

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/typescript#16]
> [!NOTE]  
> This is cleanup from https://github.com/nodejs/admin/issues/923

People interacting with the WG via https://nodejs.org/calendar are met with not enough information to join.

![image](https://github.com/user-attachments/assets/0c6ad5de-3b78-45c4-92a5-095acf9b744c)

And they won't necessarily know to look for issues like https://github.com/nodejs/typescript/issues/15

Further https://nodejs.org/en/about/get-involved/events only displays events with a zoom link.

To resolve all of this, please add https://zoom.us/j/95749675148 (which I think is a durable enough link, taken from the above issue) to the calendar.

**Comment by marco-ippolito** [comment]
Done please check again

**Comment by bmuenzenmeyer** [comment]
done!
