### ISSUE TITLE
Parameter Properties transform:  SWC vs TS (initializer relocation)

### ISSUE THREAD

**Issue by robpalme** [nodejs/typescript#3]
@marco-ippolito requested I raise this issue here due to SWC Parameter Properties differing from TS Parameter Properties.

With modern ES2022/ESNext emit, where by default it is implied that `useDefineForClassFields: true`, TS does *not* relocate class field initializers when Parameter Properties are used.  But SWC does.  So if support for the Parameter Properties transform is added in https://github.com/nodejs/node/pull/54283 then Node needs to pick which behavior it wants.

- [Comment on the Transform PR](https://github.com/nodejs/node/pull/54283#issuecomment-2282778671)
- [SWC Issue](https://github.com/swc-project/swc/issues/9418)
- [Related TS Issue](https://github.com/microsoft/TypeScript/issues/59589)

**Comment by marco-ippolito** [comment]
I'm also wondering if changing the behavior will result in a breaking change in Node.js @nodejs/typescript?

**Comment by marco-ippolito** [comment]
amaro v0.1.6 ship the updated version. Updating in core, and adding the flag in a followup PR https://github.com/nodejs/node/pull/54374

**Comment by robpalme** [comment]
This is now fixed in Node core so I am happy to close it.
